
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/7.yaml

packages:
- .

extra-deps:
- regex-tdfa-1.3.2.2
- emoji-0.1.0.2
- discord-haskell-1.16.0
