#!/bin/sh
# File generated by ocamlbuild

cd /home/skowi/Desktop/fun/Lista0

rm -f zad2.cmi
rm -f zad2.cmo
rm -f zad4.cmi
rm -f zad4.cmo
rm -f zad4.cmx
rm -f zad4.o
# Also clean the script itself
rm -f /home/skowi/Desktop/fun/Lista0/_build/sanitize.sh
